services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codepush_api
    volumes:
      - /data/azurite/data:/data
    env_file:
      - ./api/.env
    ports:
      - "3000:3000"
      - "10000:10000" 
      - "10001:10001" 
      - "10002:10002"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
